steps:
  # Build the video proxy container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform', 'linux/amd64', '-t', 'gcr.io/$PROJECT_ID/propmatch-video-proxy:$SHORT_SHA', '.']
    
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/propmatch-video-proxy:$SHORT_SHA']
    
  # Deploy to Cloud Run with optimized settings
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'propmatch-video-proxy'
      - '--image'
      - 'gcr.io/$PROJECT_ID/propmatch-video-proxy:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '5'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '60'
      - '--set-env-vars'
      - 'BUCKET_NAME=propmatch_frontend'

images:
  - 'gcr.io/$PROJECT_ID/propmatch-video-proxy:$SHORT_SHA'

options:
  substitutionOption: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
