"use client";
import React from "react";
import Link from "next/link";

const TermsOfServicePage = () => {
    return (
        <div className="min-h-screen bg-gray-50">
            {/* Header */}
            <div className="bg-white border-b border-gray-200">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="flex justify-between items-center py-6">
                        <Link href="/" className="flex items-center">
                            <span className="text-2xl font-bold text-[#1A2B6C]">PropMatch</span>
                        </Link>
                        <div className="flex space-x-4">
                            <Link href="/login" className="text-gray-600 hover:text-[#1A2B6C] px-3 py-2 rounded-md text-sm font-medium">
                                Sign In
                            </Link>
                            <Link href="/login" className="bg-[#1A2B6C] text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-blue-700">
                                Get Started
                            </Link>
                        </div>
                    </div>
                </div>
            </div>

            {/* Main Content */}
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
                <div className="bg-white rounded-lg shadow-lg p-8">
                    <h1 className="text-4xl font-bold text-gray-900 mb-4">Terms of Service</h1>
                    <p className="text-sm text-gray-600 mb-8">Last Updated: August 2025</p>
                    
                    <div className="prose prose-lg max-w-none">
                        <p className="mb-6">
                            Welcome to PropMatch.io. By using our platform, you agree to the following terms. Please read them carefully before accessing or subscribing to our services.
                        </p>

                        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">1. Services</h2>
                        <p className="mb-6">
                            PropMatch.io provides AI-powered predictions, property insights, pricing recommendations, and messaging tools designed for real estate professionals. Our services are delivered on a subscription basis and may evolve over time as we improve features.
                        </p>

                        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">2. No Guarantees</h2>
                        <p className="mb-6">
                            All predictions, scores, and recommendations provided by PropMatch.io are estimates based on data models, third-party APIs, and public information. They are not guarantees of sale, pricing, or outcomes. Users are solely responsible for verifying all property and client information before making business decisions.
                        </p>

                        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">3. Accounts and Usage</h2>
                        <p className="mb-6">
                            You must provide accurate account information and maintain the confidentiality of your login details. You are responsible for all activity under your account. PropMatch.io reserves the right to suspend or terminate accounts that violate these terms or misuse the platform.
                        </p>

                        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">4. Data and Privacy</h2>
                        <p className="mb-6">
                            By using PropMatch.io, you consent to the collection and processing of data as outlined in our Privacy Policy. You must ensure that any contact information you upload or use complies with Canada's Anti-Spam Legislation (CASL) and other applicable laws. You are responsible for obtaining necessary consent before sending outreach messages generated by our platform.
                        </p>

                        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">5. Third-Party Services</h2>
                        <p className="mb-6">
                            Our platform integrates with third-party APIs (e.g., HOUSKI, GeoApify, Google Gemini). PropMatch.io is not responsible for the accuracy, availability, or changes in these services. Use of such integrations is subject to their respective terms.
                        </p>

                        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">6. Intellectual Property</h2>
                        <p className="mb-6">
                            All software, models, workflows, and content within PropMatch.io are proprietary and owned by PropMatch.io. Users may not copy, resell, or reverse engineer any part of the platform.
                        </p>

                        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">7. Payment and Subscriptions</h2>
                        <p className="mb-6">
                            Subscriptions are billed through Stripe or other designated payment providers. All fees are non-refundable unless otherwise required by law. Plans may be upgraded or canceled at any time through your account settings.
                        </p>

                        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">8. Limitation of Liability</h2>
                        <p className="mb-6">
                            PropMatch.io is provided "as is." We are not liable for any damages, losses, or claims arising from your use of the platform, including reliance on predictions or outreach tools. Our maximum liability, if any, is limited to the fees you paid in the three months prior to the claim.
                        </p>

                        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">9. Changes to Terms</h2>
                        <p className="mb-6">
                            We may update these Terms from time to time. If material changes occur, we will notify you via email or through the platform. Continued use after updates constitutes acceptance of the new Terms.
                        </p>

                        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">10. Governing Law</h2>
                        <p className="mb-6">
                            These Terms are governed by the laws of Ontario, Canada. Any disputes will be resolved in the courts located in Toronto, Ontario.
                        </p>

                        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Contact Us</h2>
                        <p className="mb-6">
                            For questions about these Terms, please contact us at <a href="mailto:contact@propmatch.io" className="text-[#1A2B6C] hover:underline">contact@propmatch.io</a>.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TermsOfServicePage;